### PR TITLE
Update target-lexicon to 0.4.0

### PR DESCRIPTION
**Pull request by bnjbvr**
We'd like to update target-lexicon in [Cranelift](https://github.com/cranestation/cranelift), which depends on this project also using target-lexicon. So we need to update it here first.

I've done the version bump and cargo-culted the existing cases for the match in the `impl From<Architecture> for MachineTag`. Please carefully review that these new cases are correct.

### CODE REVIEW

**Comment by m4b** [comment]
Looks good to me, thanks!

**Comment by bnjbvr** [comment]
Thanks a lot! Can you release a new version of faerie too, please?

**Comment by bnjbvr** [comment]
Gentle ping: any idea when you could release a new version, please? (Otherwise Cranelift might need to depend on a fork of this crate, which would be unfortunate because we don't want to diverge from upstream.)

**Comment by bnjbvr** [comment]
(making sure to notify you for the previous comment: cc @m4b)

**Comment by sunfishcode** [comment]
I've now released this, in faerie 0.10.0.

**Comment by bnjbvr** [comment]
Thanks!

**Pull request merged**
