### PR TITLE
Updated example + export of target_lexcion

### PR DESCRIPTION
**Pull request by Cr0a3**
Hi,
In this pull request i exported the target_lexcion module, so you don't need to have it as a dependency when working with this libary.
Also, i added an example `simple.rs`, which just is the code from the readme.
In the ReadMe i made it so that you can just copy the example and it is runnable.

### CODE REVIEW

**Comment by Toni-Graphics** [comment]
@m4b

**Comment by m4b** [comment]
seems to need a rustfmt; fixing the double import warning would be nice too (not sure if CI will also fail from it, probably)

**Comment by Toni-Graphics** [comment]
Ok i will fix it

**Comment by Toni-Graphics** [comment]
I fixed the rustfmt but i didn't got the double import warning

**Comment by Toni-Graphics** [comment]
@m4b

**Comment by m4b** [comment]
macos linkage has begun failing apparently; i will merge this but i don't have time to debug why that is

**Pull request merged**
