### PR TITLE
Add link to documentation in README

### PR DESCRIPTION
**Pull request by jyn514**
I kept looking for it and not finding it :(

Is the direct link to docs.rs ok?

### CODE REVIEW

**Comment by m4b** [comment]
Hey thanks for this ! Looks good to me, although according to: https://docs.rs/about

I think docs.rs/faerie is sufficient to point to latest :)

**Comment by jyn514** [comment]
Ready for merge when you are :)

**Comment by jyn514** [comment]
Actually let me add a nice documentation badge, one sec

**Comment by jyn514** [comment]
Ok now it's good :)

**Comment by m4b** [comment]
Awesome thanks so much! :) Going to squash and merge, hope you don't mind :)

**Pull request merged**
