### PR TITLE
Update target lexicon

### PR DESCRIPTION
**Pull request by bnjbvr**
This updates target-lexicon, so we can update it in Cranelift as well. (Once that's in, it might be useful to publish a new version of this crate.)

Latest target-lexicon adds support for more architectures, and removes all the external dependencies, making it self-contained, lighter and faster to build.

### CODE REVIEW

**Comment by m4b** [comment]
I think the bss change wasn't breaking; so should be safe to release this as `0.11.1` ?

**Comment by m4b** [comment]
ok i just updated the version, and goblin to 0.1 and scroll to 0.10 while i was at it, removing last vestiges of syn; this should speed up downstream crates if we were last crates using those old versions :)

**Comment by m4b** [comment]
Ok this is published as 0.11.1; i think cranelift-object just needs to be updated with latest target-lexicon and looks like entire cranelift can upgrade :)

**Comment by philipc** [comment]
Since target-lexicon is used in the public API of faerie, a breaking change in target-lexicon is a breaking change in faerie.

**Pull request merged**
